### PR TITLE
Fix `DROP INDEX` on `ALTER TABLE`

### PR DESCRIPTION
**Pull request by stephenreay**

### CODE REVIEW

**Comment by blueness** [comment]
Are you sure about this?  I just checked the documentation: https://dev.mysql.com/doc/refman/5.7/en/drop-index.html

**Comment by blueness** [comment]
Oh wait, this is in the context of ALTER TABLE.  I see your point: https://dev.mysql.com/doc/refman/5.7/en/alter-table.html

**Comment by stephenreay** [comment]
Well it depends on how it's being used.

I'm trying to solve a bug in a downstream project - SchemaSync - where it's used in ALTER TABLE statements, not stand-alone DROP INDEX statements. 


@mmatuson indicated this was the 'correct' way to go in mmatuson/SchemaSync#49 

Having said that, possibly a better "fix" is to adjust how SchemaSync uses the generated statements.
Is IndexSchema#drop indented to be used 'stand alone' without an `ALTER TABLE`? Perhaps a flag param or additional method is needed to allow both types of `DROP`?

Lastly: please bare with me,  Python is *not* my day-to-day language, but getting this fixed for a project is quicker than writing something myself in another language.

**Comment by blueness** [comment]
@stephenreay no problem with the python, I/others can clean that up.  Just make sure DROP INDEX is always called within ALTER TABLE.

**Comment by stephenreay** [comment]
@blueness updated with what I think is a better solution.

If you agree with this approach, I'll then make use of this new functionality in a fix for mmatuson/SchemaSync#49

**Comment by stephenreay** [comment]
Actually.. I'm starting to think the original approach I had was 'more correct'. Looking at other parts of SchemaObject, I can't see anywhere that e.g ForeignKeySchema#drop() does anything to ensure it's called in the context of an `ALTER TABLE` statement. Sure, that one *has* to be called that way anyway (there is no `DROP FOREIGN KEY` outside of `ALTER TABLE`) but it seems like the assumption is mostly for them to be called in that context.

Perhaps switch the default on `alter_table` to `True`?

Thoughts, @blueness @mmatuson ??

**Comment by stephenreay** [comment]
The only other idea I have (which I think is quite fragile and too "magic" for my tastes) would be to record a `is_altering` property on the `TableSchema` class when `alter()` is called, and then reference that in `IndexSchema#drop()` to determine which types of DROP to do.

Even if that is default behaviour, I do still think a param to force one way or another is beneficial.

**Comment by stephenreay** [comment]
Ugh, I didn't mean to spam this comment thread so much.

Anyway - so it occurred to me that the `IndexSchema#create()` method *also* assumes an `ALTER TABLE` context - and that *does* have a corresponding `CREATE INDEX name ON table` mode .

**Comment by seanlook** [comment]
Simple is good. Just make sure all drop-index statement go with alter-table in code.

**Comment by stephenreay** [comment]
Any update on getting this merged in? Is there something extra I should be doing?

**Comment by stephenreay** [comment]
Can a new release be made on pypi? I'm still having to install from the archive here on GitHub rather than being able to let pip install the dependency automatically.

**Pull request merged**
